syntax = "proto3";

package kuksa.val.v1;

import "kuksa/val/v1/types.proto";

service VAL {
    rpc Subscribe(SubscribeRequest) returns (stream SubscribeResponse);
}

message SubscribeEntry {
    string         path   = 1;
    View           view   = 2;
    repeated Field fields = 3;
}

message SubscribeRequest {
    repeated SubscribeEntry entries = 1;
}

// Each update wraps a DataEntry with the set of changed fields.
message EntryUpdate {
    DataEntry      entry  = 1;
    repeated Field fields = 2;
}

message SubscribeResponse {
    repeated EntryUpdate updates = 1;
}
